spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:file:~./baza
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB